export default [
    { message: "Pikachu, use Thunderbolt!", user: "ash_k" },
    { message: "I need more potions before the next battle.", user: "brock_b" },
    { message: "Look at all the Magikarp flopping around!", user: "misty_w" },
    { message: "I just caught a rare Gyarados!", user: "ash_k" },
    { message: "You should try using a Great Ball for that one.", user: "brock_b" },
    { message: "We’re almost to the Pokémon Center!", user: "misty_w" },
    { message: "Got a badge from the Pewter Gym!", user: "ash_k" },
    { message: "Charizard, Flamethrower!", user: "ash_k" },
    { message: "Time to teach my Pokémon some new moves.", user: "brock_b" },
    { message: "My Staryu is so sparkly!", user: "misty_w" },
    { message: "Is that a shiny Pokémon?!", user: "ash_k" },
    { message: "Don't forget to stock up on Revives.", user: "brock_b" },
    { message: "Water Pokémon are the best!", user: "misty_w" },
    { message: "Gotta catch 'em all!", user: "ash_k" },
    { message: "Geodude, use Rock Throw!", user: "brock_b" },
    { message: "Psyduck, what are you doing?", user: "misty_w" },
    { message: "Evolving my Eevee into a Vaporeon!", user: "ash_k" },
    { message: "Onix, Dig!", user: "brock_b" },
    { message: "Training my Pokémon in the Viridian Forest.", user: "ash_k" },
    { message: "Team Rocket's blasting off again!", user: "narrator" },  // Adding a narrator
    { message: "Preparing for the Pokémon League!", user: "ash_k" },
    { message: "I'm going to become the very best Pokémon Breeder!", user: "brock_b" },
    { message: "Cerulean City Gym is the next challenge!", user: "misty_w" },
    { message: "Trading Pokémon with my friends!", user: "ash_k" },
    { message: "I wonder what's inside this Rare Candy?", user: "brock_b"},
    { message: "My Goldeen is so elegant!", user: "misty_w" },
    { message: "My Scyther is ready to slice and dice!", user: "guzma" },
    { message: "Plumeria, get those Grunts in line!", user: "guzma" },
    { message: "Alola! My name is Lillie, nice to meet you!", user: "lillie" },
    { message: "Nebby, get back in the bag!", user: "lillie" },
    { message: "I'm researching the Ultra Dimensions.", user: "lillie" },
    { message: "Did someone say malasadas?", user: "hau" },
    { message: "My Rowlet is taking a nap.", user: "hau" },
    { message: "I'm training to be the Island Kahuna!", user: "hau" },
    { message: "Gladion... where are you going?", user: "lillie" },
    { message: "Silvally, use Multi-Attack!", user: "gladion" },
    { message: "I don't need anyone's help.", user: "gladion" },
    { message: "Type: Null is my partner.", user: "gladion" },
    { message: "Wicke! More potions, please!", user: "guzma" },
    { message: "Don't worry, everyone. I'll heal your Pokémon.", user: "wicke" },
    { message: "Aether Foundation is dedicated to Pokémon conservation.", user: "wicke" },
    { message: "My Decidueye is ready for battle!", user: "rowlet_trainer"}, // Example of a user naming themselves after their starter
    { message: "Primarina's song is so beautiful!", user: "primarina_fan"}, // Another example
    { message: "Mightyena, use Crunch!", user: "maxie" },
    { message: "Expanding the landmass is essential for Pokémon prosperity!", user: "maxie" },
    { message: "Groudon, awaken!", user: "maxie" },
    { message: "Sharpedo, use Aqua Jet!", user: "archie" },
    { message: "Expanding the sea will create a paradise for Water Pokémon!", user: "archie" },
    { message: "Kyogre, arise!", user: "archie" },
    { message: "My Mudkip is evolving!", user: "may" },
    { message: "Contests are so much fun!", user: "may" },
    { message: "Beautifly, use Silver Wind!", user: "may" },
    { message: "My Blaziken is unstoppable!", user: "brendan" },
    { message: "I'm challenging the Elite Four!", user: "brendan" },
    { message: "Sceptile, use Leaf Blade!", user: "brendan" },
    { message: "Wally's gotten so strong!", user: "brendan" },
    { message: "My Gardevoir is my best friend.", user: "wally" },
    { message: "I'm feeling much better now.", user: "wally" },
    { message: "Steven... is so cool.", user: "wally" }, // Keeping Wally's timid personality
    { message: "My Metagross is a marvel of steel.", user: "steven" },
    { message: "The balance of nature must be preserved.", user: "steven" },
    { message: "Do you appreciate the beauty of rare stones?", user: "steven" },
    { message: "Salamence, use Fly!", user: "drake" }, // Elite Four member
    { message: "My Pokémon are burning with passion!", user: "flannery" }, // Elite Four member
    { message: "Glacia, you're going down!", user: "flannery" },
    { message: "Zekrom, strike them down!", user: "hilda" },
    { message: "Truth and ideals... what do they really mean?", user: "n" },
    { message: "Pokémon are not tools to be used!", user: "n" },
    { message: "My Zorua is quite mischievous.", user: "n" },
    { message: "Cheren, I'm going to beat you this time!", user: "hilbert" },
    { message: "Bianca, are you okay?", user: "hilda" },
    { message: "My Munna evolved into Musharna!", user: "bianca" },
    { message: "I'm still learning, but I'll become a great trainer!", user: "bianca" },
    { message: "My Serperior is so graceful.", user: "hilda"}, //Example of Starter mention
    { message: "Emboar, use Flame Charge!", user: "hilbert"},//Example of Starter mention
    { message: "I'm studying to become a Pokémon Professor like my dad.", user: "cheren" },
    { message: "My Liepard is ready for battle.", user: "cheren" },
    { message: "Plasma grunts, attack!", user: "ghetsis" },
    { message: "The world will be mine!", user: "ghetsis" },
    { message: "My Hydreigon is a force to be reckoned with.", user: "ghetsis" },
    { message: "Elesa's Emolga are so cute!", user: "elesa_fan" },  // Fan example
    { message: "Clay's Excadrill is tough!", user: "clay_challenger" }, // Challenger example
    { message: "Working hard at the Pokémon Musical!", user: "rosa" }, // From B2W2
    { message: "My Riolu is evolving!", user: "nate" }, // From B2W2
    { message: "My Swampert can handle anything!", user: "mudkip_master" },
    { message: "I'm training my Pokémon on Mt. Pyre.", user: "mt_pyre_trainer" },
    { message: "Trying to catch a Feebas in Mt. Pyre.", user: "feebas_hunter" },
    { message: "My Milotic is so beautiful!", user: "milotic_lover" },
    { message: "Exploring the underwater caves is so cool!", user: "cave_diver" },
    { message: "Watch out for the currents in Sootopolis City!", user: "sootopolis_citizen" },
    { message: "I'm going to win the Hoenn Grand Festival!", user: "contest_star" },
    { message: "My Pokémon's coolness is off the charts!", user: "coolness_trainer" },
    { message: "Gotta get those ribbons!", user: "ribbon_master" },
    { message: "Double battles are my specialty!", user: "double_battle_pro" },
    { message: "Roaming Pokémon are so hard to find!", user: "roamer_hunter" },
    { message: "Finally caught Latias!", user: "latias_catcher" }, // Or Latios depending on the game
    { message: "My Rayquaza is so powerful!", user: "rayquaza_trainer" },
    { message: "Team Aqua/Magma won't get away with this!", user: "team_aqua_magma_fighter" },
    { message: "The Safari Zone is so much fun!", user: "safari_zone_fan" },
    { message: "Trying to get a high score in the Trick House.", user: "trick_house_master" },
    { message: "Battling Winona's flying types is a challenge!", user: "winona_challenger" }, // Gym Leader example
    { message: "Tate and Liza's psychic Pokémon are tough!", user: "tate_and_liza_challenger" }, // Gym Leader example
    { message: "Norman's Slaking is so strong!", user: "norman_challenger" }, // Gym Leader Example
  ];